- name: "Installer Node.js"
  block:
    - name: Installer les dépendances
      apt:
        name:
          - curl
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes


    - name: Ajouter la clé GPG de NodeSource
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
        state: present

    - name: Ajouter le dépôt NodeSource
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }} nodistro main"
        state: present
        filename: nodesource

    - name: Installer Node.js et npm
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Installer build-essential
      apt:
        name: build-essential
        state: present

    - name: Ensure Git is installed 
      ansible.builtin.package:
        name: git
        state: present 

  when: ansible_os_family == "Debian"
    

- name: "Supprimer le répertoire de build s'il existe"
  file:
    path: "{{ build_dir }}"
    state: absent


- name: "Créer un répertoire de build vide"
  file:
    path: "{{ build_dir }}"
    state: directory
    mode: '0755'


- name: "Clone du repository"
  git:
    repo: "https://oauth:{{ TOKEN }}@{{ REGISTRY_HOST }}/{{ PROJECT_URL }}.git"
    dest: "{{ build_dir }}"
    version: "{{ CI_COMMIT_SHORT_SHA }}"
    force: true
  register: git_clone_result


- name: "Affichage du commit utilisé"
  debug:
    msg: "Commit utilisé: {{ CI_COMMIT_SHORT_SHA}} ({{ git_clone_result.after }})"


- name: "Création d'un fichier vide avec le nom du commit"
  file:
    path: "{{ build_dir }}/.{{ CI_COMMIT_SHORT_SHA}}."
    state: touch
    mode: '0644'


- name: "Vérification du fichier package.json"
  stat:
    path: "{{ build_dir }}/package.json"
  register: package_json
  

- name: "Installation des dépendances NPM"
  npm:
    path: "{{ build_dir }}"
    state: present
    production: false
  when: package_json.stat.exists


- name: "Suppression des fichiers inutiles pour le déploiement"
  file:
    path: "{{ build_dir }}/{{ item }}"
    state: absent
  loop:
    - ".git"
    - ".gitignore"
    - "README.md" 
  ignore_errors: true


- name: "Création de l'archive complète du projet"
  archive:
    path: "{{ build_dir }}/"
    dest: "{{ build_dir }}/{{ project_archive }}"
    format: gz
    exclude_path:
      - "{{ build_dir }}/{{ project_archive }}"  


- name: "Vérification de l'archive créée"
  stat:
    path: "{{ build_dir }}/{{ project_archive }}"
  register: project_archive_stat


- name: "Message de succès"
  debug:
    msg: "✅ Archive du projet créée : {{ project_archive_stat.stat.path }}"
  when: project_archive_stat.stat.exists


- name: "Message d'erreur si archive absente"
  fail:
    msg: "❌ L'archive du projet n'a pas pu être créée !"
  when: not project_archive_stat.stat.exists
