- name: "Init Build Directory"
  hosts: local_build
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
    - name: "Définir un répertoire de build "
      set_fact:
        build_dir: "/tmp/build"
      run_once: true


- name: "Build Application"
  hosts: local_build
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: "Étape 1: Build de l'application"
      import_tasks: build.yml


- name: "Deploy to Servers"
  hosts: node_server
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:

    - name: Lister tous les tags distants
      command:
        argv:
          - git
          - ls-remote
          - --tags
          - "https://gitlab-ci-token:{{ TOKEN }}@gitlab.rdmc.fr/{{ PROJECT_URL }}.git"
      register: tags_raw
      no_log: true  

    - name: Vérifier que le tag existe
      fail:
        msg: "Le tag {{ CI_TAG }} n'existe pas ou accès refusé"
      when: >
        (tags_raw.stdout_lines | select('search', 'refs/tags/' ~ CI_TAG ~ '$') | list | length) == 0

    - name: Extraire le short SHA du tag choisi
      set_fact:
        CI_COMMIT_SHORT_SHA: >-
          {{
            (tags_raw.stdout_lines
            | select('search', 'refs/tags/' ~ CI_TAG ~ '(\^{}|$)')
            | list
            | last
            ).split()[0][:8]
          }}
          

    

    - name: "Vérifier l'existence du fichier CI_COMMIT_SHORT_SHA"
      stat:
        path: "{{ LOCATION_PATH }}/{{ CI_PROJECT_NAME }}/.{{ CI_COMMIT_SHORT_SHA }}."
      register: commit_file_check
      become: true

    - block:
        - name: "Installation système"
          include_tasks: system_install.yml
          vars:
            setup_system: true

        - name: "Déploiement de l'application"
          include_tasks: deploy.yml
      when: not commit_file_check.stat.exists or force | default(false) | bool
  
  handlers:
    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
      become: true
    
    - name: "reload ssh"
      service:
        name: ssh
        state: restarted
  

  
- name: "Cleanup"
  hosts: local_build
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: "Nettoyage des fichiers temporaires de build"
      file:
        path: "{{ build_dir }}"
        state: absent
      ignore_errors: true
