all:
  children:
    local_build:
      hosts:
        localhost:
          ansible_connection: local

    node_server:
      hosts:
        raspberry1:
          localhost:
          ansible_connection: local
