all:
  children:
    local_build:
      hosts:
        localhost:
          ansible_connection: local

    node_server:
      hosts:
        # 52.157.243.79:
        #   ansible_user: azureuser
        #   ansible_ssh_private_key_file: ~/.ssh/cle.pem
        # ubuntu2:
        #   ansible_host: 127.0.0.1
        #   ansible_port: 2224
        #   ansible_user: root
        #   ansible_ssh_private_key_file: ~/.ssh/cle.pem
        # ubuntu3:
        #   ansible_host: 127.0.0.1
        #   ansible_port: 2223
        #   ansible_user: root
        #   ansible_ssh_private_key_file: ~/.ssh/cle.pem
        # ubuntu1:
        #   ansible_host: 127.0.0.1
        #   ansible_port: 2222
        #   ansible_user: root
        #   ansible_ssh_private_key_file: ~/.ssh/cle.pem

    raspberry:
      hosts:
        raspberry1:
          ansible_host: localhost
          ansible_port: 2221
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/cle.pem
        raspberry2:
          ansible_host: localhost
          ansible_port: 2222
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/cle.pem
        # raspberry3:
        #   ansible_host: localhost
        #   ansible_port: 2223
        #   ansible_user: root
        #   ansible_ssh_private_key_file: ~/.ssh/cle.pem
