
- name: "Création du groupe applicatif"
  group:
    name: "{{ app_group }}"
    state: present
  become: true


- name: "Création de l'utilisateur applicatif"
  user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    home: "{{ LOCATION_PATH }}"
    shell: /bin/bash
    create_home: true
    state: present
  become: true


- name: "Installer Node.js et PM2 "
  block:
    - name: Installer les dépendances
      apt:
        name:
          - curl
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG de NodeSource
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
        state: present

    - name: Ajouter le dépôt NodeSource
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }} nodistro main"
        state: present
        filename: nodesource

    - name: Installer Node.js et npm
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Installer build-essential
      apt:
        name: build-essential
        state: present

    - name: Installer PM2 globalement
      community.general.npm:
        name: pm2
        global: yes
        state: present

    - name: Générer service systemd  PM2
      become: yes
      become_user: "{{ app_user }}"
      shell: |
        pm2 startup systemd -u {{ app_user }} --hp /home/{{ app_user }}
        pm2 save

    - name: Activer et démarrer le service PM2 
      ansible.builtin.systemd:
        name: "pm2-{{ app_user }}"
        enabled: yes
        state: started
        daemon_reload: yes

# --- Rotation des logs ---
- name: "Configuration de la rotation des logs"
  copy:
    content: |
      {{ LOCATION_PATH }}/{{CI_PROJECT_NAME}}/logs/*.log {
          daily
          rotate 7
          compress
          delaycompress
          missingok
          notifempty
          su {{ app_user }} {{ app_group }}
      }
    dest: "/etc/logrotate.d/{{ app_user }}"
    mode: '0644'
  become: true


- name: Add user to groups video, audio, and render
  user:
    name: "{{ app_user }}"
    groups: video,audio,render
    append: yes
