- name: "Installer Node.js"
  block:
    - name: Nettoyer les anciens dépôts NodeSource
      shell: |
        rm -f /etc/apt/sources.list.d/nodesource.list
        rm -f /etc/apt/sources.list.d/nodesource*.list
        rm -f /usr/share/keyrings/nodesource.gpg
      args:
        executable: /bin/bash
      become: true

    - name: Mettre à jour le cache APT après nettoyage
      apt:
        update_cache: yes
      become: true

    - name: Installer les dépendances
      apt:
        name:
          - curl
          - software-properties-common
          - gnupg
          - mc
          - netcat-openbsd
          - cec-utils
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG de NodeSource
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
        state: present

    - name: Ajouter le dépôt NodeSource 
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      args:
        executable: /bin/bash
      become: true

    - name: Installer Node.js et npm
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Installer build-essential
      apt:
        name: build-essential
        state: present


# --- Rotation des logs ---
- name: Créer le groupe applicatif
  ansible.builtin.group:
    name: "{{ app_group }}"
    state: present

- name: Créer l'utilisateur applicatif
  ansible.builtin.user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    home: "{{ LOCATION_PATH }}"
    shell: "{{ shell }}"
    create_home: yes
    state: present

- name: "Configuration de la rotation des logs"
  copy:
    content: |
      {{ LOCATION_PATH }}/{{CI_PROJECT_NAME}}/logs/*.log {
          daily
          rotate 7
          compress
          delaycompress
          missingok
          notifempty
          
      }
    dest: "/etc/logrotate.d/{{ app_user }}"
    mode: '0644'
  become: true

- name: "Créer le dossier SSH s'il n'existe pas"
  file:
    path: "{{ LOCATION_PATH }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ app_user }}"
    group: "{{ app_group }}"


- name: "Assurer que AuthorizedKeysFile contient authorized_keys_gitlab"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AuthorizedKeysFile'
    line: 'AuthorizedKeysFile .ssh/authorized_keys .ssh/authorized_keys_gitlab'
    state: present
    backup: yes
  notify: reload ssh
  become: true

- name: "Récupérer la variable AUTHORIZED_KEYS "
  uri:
    url: "https://{{ REGISTRY_HOST }}/api/v4/projects/{{ project_id }}/variables/AUTHORIZED_KEYS"
    method: GET
    headers:
      PRIVATE-TOKEN: "{{ Env_token }}"
    return_content: yes
  register: gitlab_var

- name: "Extraire les clés SSH"
  set_fact:
    ssh_keys: "{{ gitlab_var.json.value.split('\n') }}"

- name: "Synchroniser les clés SSH"
  ansible.posix.authorized_key:
    user: "{{ app_user }}"
    key: "{{ ssh_keys | join('\n') }}"
    path: "/home/{{ app_user }}/.ssh/authorized_keys_gitlab"
    exclusive: yes
  notify: reload ssh
