- name: "Installer Node.js"
  block:
    - name: Installer les dépendances
      apt:
        name:
          - curl
          - software-properties-common
          - gnupg
          - mc
          - netcat-openbsd
          - cec-utils
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG de NodeSource
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
        state: present

    - name: Ajouter le dépôt NodeSource
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }} nodistro main"
        state: present
        filename: nodesource

    - name: Installer Node.js et npm
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Installer build-essential
      apt:
        name: build-essential
        state: present

    # --- Partie PM2 (optionnelle) ---
    # - name: Installer PM2 globalement
    #   community.general.npm:
    #     name: pm2
    #     global: yes
    #     state: present
    #
    # - name: Générer service systemd PM2
    #   become: yes
    #   shell: |
    #     env PATH=$PATH:/usr/bin pm2 startup systemd -u admin --hp /home/admin
    #
    # - name: Sauvegarder la configuration PM2 pour admin
    #   become: yes
    #   become_user: "admin"
    #   shell: |
    #     pm2 save
    #
    # - name: Activer et démarrer le service PM2
    #   ansible.builtin.systemd:
    #     name: "pm2-admin"
    #     enabled: yes
    #     state: started
    #     daemon_reload: yes
    #   become: true
    # --- Fin PM2 ---

# --- Rotation des logs ---
- name: "Configuration de la rotation des logs"
  copy:
    content: |
      {{ LOCATION_PATH }}/{{CI_PROJECT_NAME}}/logs/*.log {
          daily
          rotate 7
          compress
          delaycompress
          missingok
          notifempty
          
      }
    dest: "/etc/logrotate.d/{{ app_user }}"
    mode: '0644'
  become: true

- name: Créer le dossier .ssh s'il n'existe pas
  file:
    path: "{{ LOCATION_PATH }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: "Récupérer la variable AUTHORIZED_KEYS "
  uri:
    url: "{{ REGISTRY_HOST }}/api/v4/projects/{{ project_id }}/variables/AUTHORIZED_KEYS"
    method: GET
    headers:
      PRIVATE-TOKEN: "TOKEN"
    return_content: yes
  register: gitlab_var

- name: "Extraire les clés SSH"
  set_fact:
    ssh_keys: "{{ gitlab_var.json.value.split('\n') }}"

- name: "Synchroniser les clés SSH"
  authorized_key:
    user: "{{ app_user }}"
    key: "{{ ssh_keys | join('\n') }}"
    exclusive: yes
